-- MySQL Script generated by MySQL Workbench
-- Sat Apr 15 23:52:37 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ERP
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ERP` ;

-- -----------------------------------------------------
-- Schema ERP
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ERP` DEFAULT CHARACTER SET utf8 ;
USE `ERP` ;

-- -----------------------------------------------------
-- Table `ERP`.`office`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ERP`.`office` (
  `ofce_id` INT NOT NULL AUTO_INCREMENT,
  `ofce_name` VARCHAR(45) NULL,
  PRIMARY KEY (`ofce_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ERP`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(60) NULL,
  `user_id_office` INT NOT NULL,
  `user_login` VARCHAR(45) NULL,
  `user_password` VARCHAR(255) NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_id_office_idx` (`user_id_office` ASC) VISIBLE,
  CONSTRAINT `fk_user_id_office`
    FOREIGN KEY (`user_id_office`)
    REFERENCES `ERP`.`office` (`ofce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ERP`.`permissions` (
  `perm_id` INT NOT NULL AUTO_INCREMENT,
  `perm_name` VARCHAR(45) NULL,
  `perm_path` VARCHAR(45) NULL,
  PRIMARY KEY (`perm_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`user_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ERP`.`user_permission` (
  `uspr_id_user` INT NOT NULL,
  `uspr_id_permission` INT NOT NULL,
  `uspr_query` TINYINT(1) NULL,
  `uspr_register` TINYINT(1) NULL,
  `uspr_edit` TINYINT(1) NULL,
  `uspr_delete` TINYINT(1) NULL,
  PRIMARY KEY (`uspr_id_user`, `uspr_id_permission`),
  INDEX `uspr_permission_idx` (`uspr_id_permission` ASC) INVISIBLE,
  CONSTRAINT `uspr_user`
    FOREIGN KEY (`uspr_id_user`)
    REFERENCES `ERP`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `uspr_permission`
    FOREIGN KEY (`uspr_id_permission`)
    REFERENCES `ERP`.`permissions` (`perm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ERP`.`product` (
  `prod_id` INT NOT NULL AUTO_INCREMENT,
  `prod_name` VARCHAR(120) NULL,
  `prod_decription` TEXT NULL,
  `prod_barcode` VARCHAR(45) NULL,
  `prod_un_medida` TINYINT(100) NULL,
  `prod_price` FLOAT NULL,
  PRIMARY KEY (`prod_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ERP`.`client` (
  `clien_id` INT NOT NULL AUTO_INCREMENT,
  `clien_name` VARCHAR(80) NULL,
  `clien_cpf_cnpj` TINYINT(14) NULL,
  `clien_telefone` TINYINT(12) NULL,
  `clien_endereco` VARCHAR(60) NULL,
  `clien_bairro` VARCHAR(60) NULL,
  `clien_cidade` VARCHAR(60) NULL,
  `clien_estado` VARCHAR(2) NULL,
  `clien_numero` TINYINT(5) NULL,
  `clien_cep` TINYINT(9) NULL,
  `client_fl_inactive` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`clien_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ERP`.`orders` (
  `orde_id` INT NOT NULL AUTO_INCREMENT,
  `orde_id_client` INT NOT NULL,
  `orde_id_user` INT NOT NULL,
  `orde_dthr_venda` DATETIME NULL,
  `orde_valor_total` FLOAT NULL,
  `orde_st_venda` TINYINT(1) NULL,
  PRIMARY KEY (`orde_id`),
  INDEX `orde_user_idx` (`orde_id_user` ASC) VISIBLE,
  INDEX `orde_client_idx` (`orde_id_client` ASC) VISIBLE,
  CONSTRAINT `orde_user`
    FOREIGN KEY (`orde_id_user`)
    REFERENCES `ERP`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `orde_client`
    FOREIGN KEY (`orde_id_client`)
    REFERENCES `ERP`.`client` (`clien_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`orderitens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ERP`.`orderitens` (
  `orditen_id_order` INT NOT NULL,
  `orditen_nr_sequencia` INT NOT NULL,
  `orditen_id_produto` INT NOT NULL,
  `orditen_amount` FLOAT NULL,
  `orditen_total_price` FLOAT NULL,
  `orditen_un_price` FLOAT NULL,
  PRIMARY KEY (`orditen_id_order`, `orditen_nr_sequencia`),
  INDEX `fk_orditen_id_product_idx` (`orditen_id_produto` ASC) VISIBLE,
  CONSTRAINT `fk_orditen_id`
    FOREIGN KEY (`orditen_id_order`)
    REFERENCES `ERP`.`orders` (`orde_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orditen_id_product`
    FOREIGN KEY (`orditen_id_produto`)
    REFERENCES `ERP`.`product` (`prod_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ERP`.`office_permissions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ERP`.`office_permissions` (
  `ofpm_id_office` INT NOT NULL,
  `ofpm_id_permissions` INT NOT NULL,
  `ofpm_query` TINYINT(1) NULL,
  `ofpm_register` TINYINT(1) NULL,
  `ofpm_edit` TINYINT(1) NULL,
  `ofpm_delete` TINYINT(1) NULL,
  PRIMARY KEY (`ofpm_id_office`, `ofpm_id_permissions`),
  INDEX `fk_ofpm_id_permission_idx` (`ofpm_id_permissions` ASC) VISIBLE,
  CONSTRAINT `fk_ofpm_id_office`
    FOREIGN KEY (`ofpm_id_office`)
    REFERENCES `ERP`.`office` (`ofce_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ofpm_id_permission`
    FOREIGN KEY (`ofpm_id_permissions`)
    REFERENCES `ERP`.`permissions` (`perm_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
